#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  L_Piston,       sensorDigitalOut)
#pragma config(Sensor, dgtl2,  R_Piston,       sensorDigitalOut)
#pragma config(Sensor, dgtl3,  I_Piston,       sensorDigitalOut)
#pragma config(Sensor, dgtl4,  F_Piston,       sensorDigitalOut)
#pragma config(Sensor, dgtl5,  C_Piston,       sensorDigitalOut)
#pragma config(Sensor, dgtl6,  L_Switch,       sensorTouch)
#pragma config(Sensor, dgtl7,  R_Switch,       sensorTouch)
#pragma config(Sensor, dgtl8,  I_Encoder,      sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  L_Encoder,      sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  R_Encoder,      sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           L_Intake,      tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port2,           LF_Drive,      tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port3,           LB_Drive,      tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port4,           LF_Shifter,    tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port5,           LB_Shifter,    tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port6,           RB_Shifter,    tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port7,           RF_Shifter,    tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port8,           RB_Drive,      tmotorVex393HighSpeed, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port9,           RF_Drive,      tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port10,          R_Intake,      tmotorVex393HighSpeed, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"

//CONTROLLER MAP/////////////////////
//CH1 = N/A//////////////////////////
//CH2 = RIGHT DRIVE//////////////////
//CH3 = LEFT DRIVE///////////////////
//CH4 = N/A//////////////////////////
///5U = INTAKE IN////////////////////
///5D = INTAKE OUT///////////////////
///6U = LEFT PRELOAD LAUNCH//////////
///6D = RIGHT PRELOAD LAUNCH/////////
///7U = LAUNCH ONE///////////////////
///7D = LAUNCH TWO///////////////////
///7L = LAUNCH THREE/////////////////
///7R = LAUNCH FOUR//////////////////
///8U = N/A//////////////////////////
///8D = N/A//////////////////////////
///8L = ENGAGE 4X4 MODE (PISTON OFF)/
///8R = ENGAGE 8X0 MODE (PISTON ON)//

void prep_launch()
{

	SensorValue[L_Piston] = SensorValue[R_Piston] = SensorValue[I_Encoder] = 0;
	SensorValue[I_Piston] = 1;
}

void reset()
{
	SensorValue[L_Piston] = SensorValue[R_Piston] = 1;
	SensorValue[I_Piston]  = 0;
}

void launch1()
{

	prep_launch();

	while(SensorValue[I_Encoder] <= 9001)
	{
		motor[L_Intake] = motor[R_Intake] = 127;
	}
	motor[RF_Shifter] = motor[RB_Shifter] = -127;
	if(SensorValue[R_Switch] == 1)
	{
		motor[RF_Shifter] = motor[RB_Shifter] = -127;
		wait10Msec(10);
		motor[RF_Shifter] = motor[RB_Shifter] = 0;
	}

	reset();

}

void launch2()
{

	prep_launch();

	for (int x = 0; x <= 2; x ++)
	{
		while(SensorValue[I_Encoder] <= 9001)
		{
			motor[L_Intake] = motor[R_Intake] = 127;
		}
		motor[RF_Shifter] = motor[RB_Shifter] = -127;
		if(SensorValue[R_Switch] == 1)
		{
			motor[RF_Shifter] = motor[RB_Shifter] = -127;
			wait10Msec(10);
			motor[RF_Shifter] = motor[RB_Shifter] = 0;
		}
	}

	reset();
}

void launch3()
{
	prep_launch();

	for (int x = 0; x <= 3; x ++)
	{
		while(SensorValue[I_Encoder] <= 9001)
		{
			motor[L_Intake] = motor[R_Intake] = 127;
		}
		motor[RF_Shifter] = motor[RB_Shifter] = -127;
		if(SensorValue[R_Switch] == 1)
		{
			motor[RF_Shifter] = motor[RB_Shifter] = -127;
			wait10Msec(10);
			motor[RF_Shifter] = motor[RB_Shifter] = 0;
		}
	}

	reset();
}

void launch4()
{

	prep_launch();

	for (int x = 0; x <= 4; x ++)
	{
		while(SensorValue[I_Encoder] <= 9001)
		{
			motor[L_Intake] = motor[R_Intake] = 127;
		}
		motor[RF_Shifter] = motor[RB_Shifter] = -127;
		if(SensorValue[R_Switch] == 1)
		{
			motor[RF_Shifter] = motor[RB_Shifter] = -127;
			wait10Msec(10);
			motor[RF_Shifter] = motor[RB_Shifter] = 0;
		}
	}

	reset();

}

void control()
{

	//INTAKE
	if(vexRT[Btn5U] == 1)
	{
		motor[L_Intake] = motor[R_Intake] = 127;
	}
	else if(vexRT[Btn5D] == 1)
	{
		motor[L_Intake] = motor[R_Intake] = -127;
	}
	else
	{
		motor[L_Intake] = motor[R_Intake] = 0;
	}

	//SHIFTER (MANUAL OVERRIDE)
	if(vexRT[Btn8L] == 1)
	{
		SensorValue[L_Piston] = 0;
		SensorValue[R_Piston] = 0;
	}
	else if(vexRT[Btn8R] == 1)
	{
		SensorValue[L_Piston] = 1;
		SensorValue[R_Piston] = 1;
	}

	//CATAPULT
	if(vexRT[Btn7R] == 1)
	{
		launch1();
	}
	else if(vexRT[Btn7U] == 1)
	{
		launch2();
	}
	else if (vexRT[Btn7L] == 1)
	{
		launch3();
	}
	else if (vexRT[Btn7D] == 1)
	{
		launch4();
	}

}

void pre_auton()
{

	bStopTasksBetweenModes = true;

}

task autonomous()
{

	motor[LF_Shifter] = motor[LB_Shifter] = -127;
	motor[RF_Shifter] = motor[RB_Shifter] = -127;
	wait10Msec(50);
	motor[LF_Shifter] = motor[LB_Shifter] = 0;
	motor[RF_Shifter] = motor[RB_Shifter] = 0;

}

task usercontrol()
{

	SensorValue[L_Piston] = SensorValue[R_Piston] = 1;

	while (true)
	{

		//EIGHT-MOTOR DRIVE

		while(SensorValue[L_Piston] == 1)
		{

			motor[RF_Drive] = vexRT[Ch2];
			motor[RB_Drive] = vexRT[Ch2];
			motor[RF_Shifter] = vexRT[Ch2];
			motor[RB_Shifter] = vexRT[Ch2];
			motor[LF_Drive] = vexRT[Ch3];
			motor[LB_Drive] = vexRT[Ch3];
			motor[LF_Shifter] = vexRT[Ch3];
			motor[LB_Shifter] = vexRT[Ch3];

			control();

		}

		//4x4 CATAPULT/DRIVE

		while(SensorValue[L_Piston] == 0)
		{

			motor[RF_Drive] = vexRT[Ch2];
			motor[RB_Drive] = vexRT[Ch2];
			motor[LF_Drive] = vexRT[Ch3];
			motor[LB_Drive] = vexRT[Ch3];

			//LEFT PRELOAD
			if(vexRT[Btn6U] == 1)
			{
				motor[LF_Shifter] = motor[LB_Shifter] = -127;
			}

			if(SensorValue[L_Switch] == 1)
			{
				wait10Msec(30);
				motor[LF_Shifter] = motor[LB_Shifter] = 5;
			}

			//RIGHT PRELOAD
			if(vexRT[Btn6D] == 1)
			{
				motor[RF_Shifter] = motor[RB_Shifter] = -127;
			}

			if(SensorValue[R_Switch] == 1)
			{
				wait10Msec(9);
				motor[RF_Shifter] = motor[RB_Shifter] = 5;
			}

			control();

		}
	}
}
